<?php

use App\Models\Currency;
use Illuminate\Database\Seeder;

/**
 * Class InsertCurrencies
 * Responsible for inserting the list of currencies.
 */
class InsertCurrencies extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Currency::insert([
            ['initial' => 'AED', 'name' => 'UAE Dirham'],
            ['initial' => 'AFN', 'name' => 'Afghani'],
            ['initial' => 'ALL', 'name' => 'Lek	Lek'],
            ['initial' => 'AMD', 'name' => 'Armenian Dram'],
            ['initial' => 'ANG', 'name' => 'Netherlands Antillian Guilder'],
            ['initial' => 'AOA', 'name' => 'Kwanza'],
            ['initial' => 'ARS', 'name' => 'Argentine Peso'],
            ['initial' => 'AUD', 'name' => 'Australian Dollar'],
            ['initial' => 'AWG', 'name' => 'Aruban Guilder'],
            ['initial' => 'AZN', 'name' => 'Azerbaijanian Manat'],
            ['initial' => 'BAM', 'name' => 'Convertible Marks'],
            ['initial' => 'BBD', 'name' => 'Barbados Dollar'],
            ['initial' => 'BDT', 'name' => 'Taka'],
            ['initial' => 'BGN', 'name' => 'Bulgarian Lev'],
            ['initial' => 'BHD', 'name' => 'Bahraini Dinar'],
            ['initial' => 'BIF', 'name' => 'Burundi Franc'],
            ['initial' => 'BMD', 'name' => 'Bermudian Dollar (customarily known as Bermuda Dollar)'],
            ['initial' => 'BND', 'name' => 'Brunei Dollar'],
            ['initial' => 'BOB', 'name' => 'BOV	Boliviano Mvdol'],
            ['initial' => 'BRL', 'name' => 'Brazilian Real'],
            ['initial' => 'BSD', 'name' => 'Bahamian Dollar'],
            ['initial' => 'BWP', 'name' => 'Pula'],
            ['initial' => 'BYR', 'name' => 'Belarussian Ruble'],
            ['initial' => 'BZD', 'name' => 'Belize Dollar'],
            ['initial' => 'CAD', 'name' => 'Canadian Dollar	$'],
            ['initial' => 'CDF', 'name' => 'Congolese Franc'],
            ['initial' => 'CHF', 'name' => 'Swiss Franc	CHF'],
            ['initial' => 'CLP', 'name' => 'CLF	Chilean Peso Unidades de fomento'],
            ['initial' => 'CNY', 'name' => 'Yuan Renminbi'],
            ['initial' => 'COP', 'name' => 'COU	Colombian Peso Unidad de Valor Real'],
            ['initial' => 'CRC', 'name' => 'Costa Rican Colon'],
            ['initial' => 'CUP', 'name' => 'CUC	Cuban Peso Peso Convertible'],
            ['initial' => 'CVE', 'name' => 'Cape Verde Escudo'],
            ['initial' => 'CZK', 'name' => 'Czech Koruna'],
            ['initial' => 'DJF', 'name' => 'Djibouti Franc'],
            ['initial' => 'DKK', 'name' => 'Danish Krone'],
            ['initial' => 'DOP', 'name' => 'Dominican Peso'],
            ['initial' => 'DZD', 'name' => 'Algerian Dinar'],
            ['initial' => 'EEK', 'name' => 'Kroon'],
            ['initial' => 'EGP', 'name' => 'Egyptian Pound'],
            ['initial' => 'ERN', 'name' => 'Nakfa'],
            ['initial' => 'ETB', 'name' => 'Ethiopian Birr'],
            ['initial' => 'EUR', 'name' => 'Euro'],
            ['initial' => 'FJD', 'name' => 'Fiji Dollar	$'],
            ['initial' => 'FKP', 'name' => 'Falkland Islands Pound'],
            ['initial' => 'GBP', 'name' => 'Pound Sterling'],
            ['initial' => 'GEL', 'name' => 'Lari'],
            ['initial' => 'GHS', 'name' => 'Cedi'],
            ['initial' => 'GIP', 'name' => 'Gibraltar Pound'],
            ['initial' => 'GMD', 'name' => 'Dalasi'],
            ['initial' => 'GNF', 'name' => 'Guinea Franc'],
            ['initial' => 'GTQ', 'name' => 'Quetzal'],
            ['initial' => 'GYD', 'name' => 'Guyana Dollar'],
            ['initial' => 'HKD', 'name' => 'Hong Kong Dollar'],
            ['initial' => 'HNL', 'name' => 'Lempira	L'],
            ['initial' => 'HRK', 'name' => 'Croatian Kuna'],
            ['initial' => 'HTG', 'name' => 'USD	Gourde US Dollar'],
            ['initial' => 'HUF', 'name' => 'Forint'],
            ['initial' => 'IDR', 'name' => 'Rupiah'],
            ['initial' => 'ILS', 'name' => 'New Israeli Sheqel'],
            ['initial' => 'INR', 'name' => 'Indian Rupee'],
            ['initial' => 'INR', 'name' => 'BTN	Indian Rupee Ngultrum'],
            ['initial' => 'IQD', 'name' => 'Iraqi Dinar'],
            ['initial' => 'IRR', 'name' => 'Iranian Rial'],
            ['initial' => 'ISK', 'name' => 'Iceland Krona'],
            ['initial' => 'JMD', 'name' => 'Jamaican Dollar	'],
            ['initial' => 'JOD', 'name' => 'Jordanian Dinar'],
            ['initial' => 'JPY', 'name' => 'Yen'],
            ['initial' => 'KES', 'name' => 'Kenyan Shilling'],
            ['initial' => 'KGS', 'name' => 'Som'],
            ['initial' => 'KHR', 'name' => 'Riel'],
            ['initial' => 'KMF', 'name' => 'Comoro Franc'],
            ['initial' => 'KPW', 'name' => 'North Korean Won'],
            ['initial' => 'KRW', 'name' => 'Won'],
            ['initial' => 'KWD', 'name' => 'Kuwaiti Dinar'],
            ['initial' => 'KYD', 'name' => 'Cayman Islands Dollar'],
            ['initial' => 'KZT', 'name' => 'Tenge'],
            ['initial' => 'LAK', 'name' => 'Kip'],
            ['initial' => 'LBP', 'name' => 'Lebanese Pound'],
            ['initial' => 'LKR', 'name' => 'Sri Lanka Rupee'],
            ['initial' => 'LRD', 'name' => 'Liberian Dollar'],
            ['initial' => 'LTL', 'name' => 'Lithuanian Litas'],
            ['initial' => 'LVL', 'name' => 'Latvian Lats'],
            ['initial' => 'LYD', 'name' => 'Libyan Dinar'],
            ['initial' => 'MAD', 'name' => 'Moroccan Dirham'],
            ['initial' => 'MDL', 'name' => 'Moldovan Leu'],
            ['initial' => 'MGA', 'name' => 'Malagasy Ariary'],
            ['initial' => 'MKD', 'name' => 'Denar'],
            ['initial' => 'MMK', 'name' => 'Kyat'],
            ['initial' => 'MNT', 'name' => 'Tugrik'],
            ['initial' => 'MOP', 'name' => 'Pataca	'],
            ['initial' => 'MRO', 'name' => 'Ouguiya	'],
            ['initial' => 'MUR', 'name' => 'Mauritius Rupee'],
            ['initial' => 'MVR', 'name' => 'Rufiyaa'],
            ['initial' => 'MWK', 'name' => 'Kwacha'],
            ['initial' => 'MXN', 'name' => 'MXV	Mexican Peso Mexican Unidad de Inversion (UDI)'],
            ['initial' => 'MYR', 'name' => 'Malaysian Ringgit'],
            ['initial' => 'MZN', 'name' => 'Metical	MT'],
            ['initial' => 'NGN', 'name' => 'Naira'],
            ['initial' => 'NIO', 'name' => 'Cordoba Oro'],
            ['initial' => 'NOK', 'name' => 'Norwegian Krone'],
            ['initial' => 'NPR', 'name' => 'Nepalese Rupee'],
            ['initial' => 'NZD', 'name' => 'New Zealand Dollar'],
            ['initial' => 'OMR', 'name' => 'Rial Omani'],
            ['initial' => 'PAB', 'name' => 'USD	Balboa US Dollar'],
            ['initial' => 'PEN', 'name' => 'Nuevo Sol'],
            ['initial' => 'PGK', 'name' => 'Kina'],
            ['initial' => 'PHP', 'name' => 'Philippine Peso	Php'],
            ['initial' => 'PKR', 'name' => 'Pakistan Rupee'],
            ['initial' => 'PLN', 'name' => 'Zloty'],
            ['initial' => 'PYG', 'name' => 'Guarani	Gs'],
            ['initial' => 'QAR', 'name' => 'Qatari Rial'],
            ['initial' => 'RON', 'name' => 'New Leu	lei'],
            ['initial' => 'RSD', 'name' => 'Serbian Dinar'],
            ['initial' => 'RUB', 'name' => 'Russian Ruble'],
            ['initial' => 'RWF', 'name' => 'Rwanda Franc'],
            ['initial' => 'SAR', 'name' => 'Saudi Riyal'],
            ['initial' => 'SBD', 'name' => 'Solomon Islands Dollar'],
            ['initial' => 'SCR', 'name' => 'Seychelles Rupee'],
            ['initial' => 'SDG', 'name' => 'Sudanese Pound'],
            ['initial' => 'SEK', 'name' => 'Swedish Krona'],
            ['initial' => 'SGD', 'name' => 'Singapore Dollar'],
            ['initial' => 'SHP', 'name' => 'Saint Helena Pound'],
            ['initial' => 'SLL', 'name' => 'Leone'],
            ['initial' => 'SOS', 'name' => 'Somali Shilling'],
            ['initial' => 'SRD', 'name' => 'Surinam Dollar'],
            ['initial' => 'STD', 'name' => 'Dobra'],
            ['initial' => 'SVC', 'name' => 'USD	El Salvador Colon US Dollar'],
            ['initial' => 'SYP', 'name' => 'Syrian Pound'],
            ['initial' => 'SZL', 'name' => 'Lilangeni'],
            ['initial' => 'THB', 'name' => 'Baht'],
            ['initial' => 'TJS', 'name' => 'Somoni'],
            ['initial' => 'TMT', 'name' => 'Manat'],
            ['initial' => 'TND', 'name' => 'Tunisian Dinar'],
            ['initial' => 'TOP', 'name	 => Paanga'],
            ['initial' => 'TRY', 'name' => 'Turkish Lira'],
            ['initial' => 'TTD', 'name	 => Trinidad and Tobago Dollar	TT$'],
            ['initial' => 'TWD', 'name' => 'New Taiwan Dollar'],
            ['initial' => 'TZS', 'name' => 'Tanzanian Shilling'],
            ['initial' => 'UAH', 'name' => 'Hryvnia'],
            ['initial' => 'UGX', 'name' => 'Uganda Shilling'],
            ['initial' => 'USD', 'name' => 'US Dollar'],
            ['initial' => 'UYU', 'name' => 'UYI	Peso Uruguayo Uruguay Peso en Unidades Indexadas'],
            ['initial' => 'UZS', 'name' => 'Uzbekistan Sum'],
            ['initial' => 'VEF', 'name' => 'Bolivar Fuerte'],
            ['initial' => 'VND', 'name' => 'Dong'],
            ['initial' => 'VUV', 'name' => 'Vatu'],
            ['initial' => 'WST', 'name' => 'Tala'],
            ['initial' => 'XAF', 'name' => 'CFA Franc BEAC'],
            ['initial' => 'XAG', 'name' => 'Silver'],
            ['initial' => 'XAU', 'name' => 'Gold'],
            ['initial' => 'XBA', 'name' => 'Bond Markets Units European Composite Unit (EURCO)'],
            ['initial' => 'XBB', 'name' => 'European Monetary Unit (E.M.U.-6)'],
            ['initial' => 'XBC', 'name' => 'European Unit of Account 9(E.U.A.-9)'],
            ['initial' => 'XBD', 'name' => 'European Unit of Account 17(E.U.A.-17)'],
            ['initial' => 'XCD', 'name' => 'East Caribbean Dollar'],
            ['initial' => 'XDR', 'name' => 'SDR'],
            ['initial' => 'XFU', 'name' => 'UIC-Franc'],
            ['initial' => 'XOF', 'name' => 'CFA Franc BCEAO'],
            ['initial' => 'XPD', 'name' => 'Palladium'],
            ['initial' => 'XPF', 'name' => 'CFP Franc'],
            ['initial' => 'XPT', 'name' => 'Platinum'],
            ['initial' => 'XTS', 'name' => 'Codes specifically reserved for testing purposes'],
            ['initial' => 'YER', 'name' => 'Yemeni Rial'],
            ['initial' => 'ZAR', 'name' => 'Rand'],
            ['initial' => 'ZAR', 'name' => 'LSL	Rand Loti'],
            ['initial' => 'ZAR', 'name' => 'NAD	Rand Namibia Dollar'],
            ['initial' => 'ZMK', 'name' => 'Zambian Kwacha'],
            ['initial' => 'ZWL', 'name' => 'Zimbabwe Dollar']
        ]);
    }
}
