<?php

use App\Models\Country;
use Illuminate\Database\Seeder;

/**
 * Class InsertCountries
 *
 * @author Gabriel Anhaia <anhaia.gabriel@gmail.com>
 */
class InsertCountry extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Country::insert([
            ['initial' => 'AL', 'name' => 'Albania'],
            ['initial' => 'DZ', 'name' => 'Algeria'],
            ['initial' => 'AS', 'name' => 'American Samoa'],
            ['initial' => 'AD', 'name' => 'Andorra'],
            ['initial' => 'AO', 'name' => 'Angola'],
            ['initial' => 'AI', 'name' => 'Anguilla'],
            ['initial' => 'AQ', 'name' => 'Antarctica'],
            ['initial' => 'AG', 'name' => 'Antigua And Barbuda'],
            ['initial' => 'AR', 'name' => 'Argentina'],
            ['initial' => 'AM', 'name' => 'Armenia'],
            ['initial' => 'AW', 'name' => 'Aruba'],
            ['initial' => 'AU', 'name' => 'Australia'],
            ['initial' => 'AT', 'name' => 'Austria'],
            ['initial' => 'AZ', 'name' => 'Azerbaijan'],
            ['initial' => 'BS', 'name' => 'Bahamas'],
            ['initial' => 'BH', 'name' => 'Bahrain'],
            ['initial' => 'BD', 'name' => 'Bangladesh'],
            ['initial' => 'BB', 'name' => 'Barbados'],
            ['initial' => 'BY', 'name' => 'Belarus'],
            ['initial' => 'BE', 'name' => 'Belgium'],
            ['initial' => 'BZ', 'name' => 'Belize'],
            ['initial' => 'BJ', 'name' => 'Benin'],
            ['initial' => 'BM', 'name' => 'Bermuda'],
            ['initial' => 'BT', 'name' => 'Bhutan'],
            ['initial' => 'BO', 'name' => 'Bolivia'],
            ['initial' => 'BA', 'name' => 'Bosnia And Herzegovina'],
            ['initial' => 'BW', 'name' => 'Botswana'],
            ['initial' => 'BV', 'name' => 'Bouvet Island'],
            ['initial' => 'BR', 'name' => 'Brazil'],
            ['initial' => 'IO', 'name' => 'British Indian Ocean Territory'],
            ['initial' => 'BN', 'name' => 'Brunei Darussalam'],
            ['initial' => 'BG', 'name' => 'Bulgaria'],
            ['initial' => 'BF', 'name' => 'Burkina Faso'],
            ['initial' => 'BI', 'name' => 'Burundi'],
            ['initial' => 'KH', 'name' => 'Cambodia'],
            ['initial' => 'CM', 'name' => 'Cameroon'],
            ['initial' => 'CA', 'name' => 'Canada'],
            ['initial' => 'CV', 'name' => 'Cape Verde'],
            ['initial' => 'KY', 'name' => 'Cayman Islands'],
            ['initial' => 'CF', 'name' => 'Central African Republic'],
            ['initial' => 'TD', 'name' => 'Chad'],
            ['initial' => 'CL', 'name' => 'Chile'],
            ['initial' => 'CN', 'name' => 'China'],
            ['initial' => 'CX', 'name' => 'Christmas Island'],
            ['initial' => 'CC', 'name' => 'Cocos (keeling) Islands'],
            ['initial' => 'CO', 'name' => 'Colombia'],
            ['initial' => 'KM', 'name' => 'Comoros'],
            ['initial' => 'CG', 'name' => 'Congo'],
            ['initial' => 'CD', 'name' => 'Congo, The Democratic Republic Of The'],
            ['initial' => 'CK', 'name' => 'Cook Islands'],
            ['initial' => 'CR', 'name' => 'Costa Rica'],
            ['initial' => 'CI', 'name' => 'Cote Divoire'],
            ['initial' => 'CHR', 'name' => 'Crooatia'],
            ['initial' => 'CU', 'name' => 'Cuba'],
            ['initial' => 'CY', 'name' => 'Cyprus'],
            ['initial' => 'CZ', 'name' => 'Czech Republic'],
            ['initial' => 'DK', 'name' => 'Denmark'],
            ['initial' => 'DJ', 'name' => 'Djibouti'],
            ['initial' => 'DM', 'name' => 'Dominica'],
            ['initial' => 'DO', 'name' => 'Dominican Republic'],
            ['initial' => 'TP', 'name' => 'East Timor'],
            ['initial' => 'EC', 'name' => 'Ecuador'],
            ['initial' => 'EG', 'name' => 'Egypt'],
            ['initial' => 'SV', 'name' => 'El Salvador'],
            ['initial' => 'GQ', 'name' => 'Equatorial Guinea'],
            ['initial' => 'ER', 'name' => 'Eritrea'],
            ['initial' => 'EE', 'name' => 'Estonia'],
            ['initial' => 'ET', 'name' => 'Ethiopia'],
            ['initial' => 'FK', 'name' => 'Falkland Islands (malvinas)'],
            ['initial' => 'FO', 'name' => 'Faroe Islands'],
            ['initial' => 'FJ', 'name' => 'Fiji'],
            ['initial' => 'FI', 'name' => 'Finland'],
            ['initial' => 'FR', 'name' => 'France'],
            ['initial' => 'GF', 'name' => 'French Guiana'],
            ['initial' => 'PF', 'name' => 'French Polynesia'],
            ['initial' => 'TF', 'name' => 'French Southern Territories'],
            ['initial' => 'GA', 'name' => 'Gabon'],
            ['initial' => 'GM', 'name' => 'Gambia'],
            ['initial' => 'GE', 'name' => 'Georgia'],
            ['initial' => 'DE', 'name' => 'Germany'],
            ['initial' => 'GH', 'name' => 'Ghana'],
            ['initial' => 'GI', 'name' => 'Gibraltar'],
            ['initial' => 'GR', 'name' => 'Greece'],
            ['initial' => 'GL', 'name' => 'Greenland'],
            ['initial' => 'GD', 'name' => 'Grenada'],
            ['initial' => 'GP', 'name' => 'Guadeloupe'],
            ['initial' => 'GU', 'name' => 'Guam'],
            ['initial' => 'GT', 'name' => 'Guatemala'],
            ['initial' => 'GN', 'name' => 'Guinea'],
            ['initial' => 'GW', 'name' => 'Guinea-bissau'],
            ['initial' => 'GY', 'name' => 'Guyana'],
            ['initial' => 'HT', 'name' => 'Haiti'],
            ['initial' => 'HM', 'name' => 'Heard Island And Mcdonald Islands'],
            ['initial' => 'VA', 'name' => 'Holy See (vatican City State)'],
            ['initial' => 'HN', 'name' => 'Honduras'],
            ['initial' => 'HK', 'name' => 'Hong Kong'],
            ['initial' => 'HU', 'name' => 'Hungary'],
            ['initial' => 'IS', 'name' => 'Iceland'],
            ['initial' => 'IN', 'name' => 'India'],
            ['initial' => 'ID', 'name' => 'Indonesia'],
            ['initial' => 'IR', 'name' => 'Iran, Islamic Republic Of'],
            ['initial' => 'IQ', 'name' => 'Iraq'],
            ['initial' => 'IE', 'name' => 'Ireland'],
            ['initial' => 'IL', 'name' => 'Israel'],
            ['initial' => 'IT', 'name' => 'Italy'],
            ['initial' => 'JM', 'name' => 'Jamaica'],
            ['initial' => 'JP', 'name' => 'Japan'],
            ['initial' => 'JO', 'name' => 'Jordan'],
            ['initial' => 'KZ', 'name' => 'Kazakstan'],
            ['initial' => 'KE', 'name' => 'Kenya'],
            ['initial' => 'KI', 'name' => 'Kiribati'],
            ['initial' => 'KP', 'name' => 'Korea, Democratic Peoples Republic Of'],
            ['initial' => 'KV', 'name' => 'Kosovo'],
            ['initial' => 'KW', 'name' => 'Kuwait'],
            ['initial' => 'KG', 'name' => 'Kyrgyzstan'],
            ['initial' => 'LA', 'name' => 'Lao Peoples Democratic Republic'],
            ['initial' => 'LV', 'name' => 'Latvia'],
            ['initial' => 'LB', 'name' => 'Lebanon'],
            ['initial' => 'LS', 'name' => 'Lesotho'],
            ['initial' => 'LR', 'name' => 'Liberia'],
            ['initial' => 'LY', 'name' => 'Libyan Arab Jamahiriya'],
            ['initial' => 'LI', 'name' => 'Liechtenstein'],
            ['initial' => 'LT', 'name' => 'Lithuania'],
            ['initial' => 'LU', 'name' => 'Luxembourg'],
            ['initial' => 'MO', 'name' => 'Macau'],
            ['initial' => 'MK', 'name' => 'Macedonia, The Former Yugoslav Republic Of'],
            ['initial' => 'MG', 'name' => 'Madagascar'],
            ['initial' => 'MW', 'name' => 'Malawi'],
            ['initial' => 'MY', 'name' => 'Malaysia'],
            ['initial' => 'MV', 'name' => 'Maldives'],
            ['initial' => 'ML', 'name' => 'Mali'],
            ['initial' => 'MT', 'name' => 'Malta'],
            ['initial' => 'MH', 'name' => 'Marshall Islands'],
            ['initial' => 'MQ', 'name' => 'Martinique'],
            ['initial' => 'MR', 'name' => 'Mauritania'],
            ['initial' => 'MU', 'name' => 'Mauritius'],
            ['initial' => 'YT', 'name' => 'Mayotte'],
            ['initial' => 'MX', 'name' => 'Mexico'],
            ['initial' => 'FM', 'name' => 'Micronesia, Federated States Of'],
            ['initial' => 'MD', 'name' => 'Moldova, Republic Of'],
            ['initial' => 'MC', 'name' => 'Monaco'],
            ['initial' => 'MN', 'name' => 'Mongolia'],
            ['initial' => 'MS', 'name' => 'Montserrat'],
            ['initial' => 'ME', 'name' => 'Montenegro'],
            ['initial' => 'MA', 'name' => 'Morocco'],
            ['initial' => 'MZ', 'name' => 'Mozambique'],
            ['initial' => 'MM', 'name' => 'Myanmar'],
            ['initial' => 'NA', 'name' => 'Namibia'],
            ['initial' => 'NR', 'name' => 'Nauru'],
            ['initial' => 'NP', 'name' => 'Nepal'],
            ['initial' => 'NL', 'name' => 'Netherlands'],
            ['initial' => 'AN', 'name' => 'Netherlands Antilles'],
            ['initial' => 'NC', 'name' => 'New Caledonia'],
            ['initial' => 'NZ', 'name' => 'New Zealand'],
            ['initial' => 'NI', 'name' => 'Nicaragua'],
            ['initial' => 'NE', 'name' => 'Niger'],
            ['initial' => 'NG', 'name' => 'Nigeria'],
            ['initial' => 'NU', 'name' => 'Niue'],
            ['initial' => 'NF', 'name' => 'Norfolk Island'],
            ['initial' => 'MP', 'name' => 'Northern Mariana Islands'],
            ['initial' => 'NO', 'name' => 'Norway'],
            ['initial' => 'OM', 'name' => 'Oman'],
            ['initial' => 'PK', 'name' => 'Pakistan'],
            ['initial' => 'PW', 'name' => 'Palau'],
            ['initial' => 'PS', 'name' => 'Palestinian Territory, Occupied'],
            ['initial' => 'PA', 'name' => 'Panama'],
            ['initial' => 'PG', 'name' => 'Papua New Guinea'],
            ['initial' => 'PY', 'name' => 'Paraguay'],
            ['initial' => 'PE', 'name' => 'Peru'],
            ['initial' => 'PH', 'name' => 'Philippines'],
            ['initial' => 'PN', 'name' => 'Pitcairn'],
            ['initial' => 'PL', 'name' => 'Poland'],
            ['initial' => 'PT', 'name' => 'Portugal'],
            ['initial' => 'PR', 'name' => 'Puerto Rico'],
            ['initial' => 'QA', 'name' => 'Qatar'],
            ['initial' => 'RE', 'name' => 'Reunion'],
            ['initial' => 'RO', 'name' => 'Romania'],
            ['initial' => 'RU', 'name' => 'Russian Federation'],
            ['initial' => 'RW', 'name' => 'Rwanda'],
            ['initial' => 'SH', 'name' => 'Saint Helena'],
            ['initial' => 'KN', 'name' => 'Saint Kitts And Nevis'],
            ['initial' => 'LC', 'name' => 'Saint Lucia'],
            ['initial' => 'PM', 'name' => 'Saint Pierre And Miquelon'],
            ['initial' => 'VC', 'name' => 'Saint Vincent And The Grenadines'],
            ['initial' => 'WS', 'name' => 'Samoa'],
            ['initial' => 'SM', 'name' => 'San Marino'],
            ['initial' => 'ST', 'name' => 'Sao Tome And Principe'],
            ['initial' => 'SA', 'name' => 'Saudi Arabia'],
            ['initial' => 'SN', 'name' => 'Senegal'],
            ['initial' => 'RS', 'name' => 'Serbia'],
            ['initial' => 'SC', 'name' => 'Seychelles'],
            ['initial' => 'SL', 'name' => 'Sierra Leone'],
            ['initial' => 'SG', 'name' => 'Singapore'],
            ['initial' => 'SK', 'name' => 'Slovakia'],
            ['initial' => 'SI', 'name' => 'Slovenia'],
            ['initial' => 'SB', 'name' => 'Solomon Islands'],
            ['initial' => 'SO', 'name' => 'Somalia'],
            ['initial' => 'ZA', 'name' => 'South Africa'],
            ['initial' => 'GS', 'name' => 'South Georgia And The South Sandwich Islands'],
            ['initial' => 'ES', 'name' => 'Spain'],
            ['initial' => 'LK', 'name' => 'Sri Lanka'],
            ['initial' => 'SD', 'name' => 'Sudan'],
            ['initial' => 'SR', 'name' => 'Suriname'],
            ['initial' => 'SJ', 'name' => 'Svalbard And Jan Mayen'],
            ['initial' => 'SZ', 'name' => 'Swaziland'],
            ['initial' => 'SE', 'name' => 'Sweden'],
            ['initial' => 'CH', 'name' => 'Switzerland'],
            ['initial' => 'SY', 'name' => 'Syrian Arab Republic'],
            ['initial' => 'TW', 'name' => 'Taiwan, Province Of China'],
            ['initial' => 'TJ', 'name' => 'Tajikistan'],
            ['initial' => 'TZ', 'name' => 'Tanzania, United Republic Of'],
            ['initial' => 'TH', 'name' => 'Thailand'],
            ['initial' => 'TG', 'name' => 'Togo'],
            ['initial' => 'TK', 'name' => 'Tokelau'],
            ['initial' => 'TO', 'name' => 'Tonga'],
            ['initial' => 'TT', 'name' => 'Trinidad And Tobago'],
            ['initial' => 'TN', 'name' => 'Tunisia'],
            ['initial' => 'TR', 'name' => 'Turkey'],
            ['initial' => 'TM', 'name' => 'Turkmenistan'],
            ['initial' => 'TC', 'name' => 'Turks And Caicos Islands'],
            ['initial' => 'TV', 'name' => 'Tuvalu'],
            ['initial' => 'UG', 'name' => 'Uganda'],
            ['initial' => 'UA', 'name' => 'Ukraine'],
            ['initial' => 'AE', 'name' => 'United Arab Emirates'],
            ['initial' => 'GB', 'name' => 'United Kingdom'],
            ['initial' => 'US', 'name' => 'United States'],
            ['initial' => 'UM', 'name' => 'United States Minor Outlying Islands'],
            ['initial' => 'UY', 'name' => 'Uruguay'],
            ['initial' => 'UZ', 'name' => 'Uzbekistan'],
            ['initial' => 'VU', 'name' => 'Vanuatu'],
            ['initial' => 'VE', 'name' => 'Venezuela'],
            ['initial' => 'VN', 'name' => 'Viet Nam'],
            ['initial' => 'VG', 'name' => 'Virgin Islands, British'],
            ['initial' => 'VI', 'name' => 'Virgin Islands, U.s.'],
            ['initial' => 'WF', 'name' => 'Wallis And Futuna'],
            ['initial' => 'EH', 'name' => 'Western Sahara'],
            ['initial' => 'YE', 'name' => 'Yemen'],
            ['initial' => 'ZM', 'name' => 'Zambia'],
            ['initial' => 'ZW', 'name' => 'Zimbabwe '],
        ]);
    }
}
